#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vsqlite
Version  : 0.3.13
Release  : 4
URL      : https://github.com/vinzenz/vsqlite--/archive/0.3.13.tar.gz
Source0  : https://github.com/vinzenz/vsqlite--/archive/0.3.13.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: vsqlite-lib
BuildRequires : boost-dev
BuildRequires : sqlite-autoconf-dev

%description
A welldesigned and portable SQLite3 Wrapper for C++

%package dev
Summary: dev components for the vsqlite package.
Group: Development
Requires: vsqlite-lib
Provides: vsqlite-devel

%description dev
dev components for the vsqlite package.


%package lib
Summary: lib components for the vsqlite package.
Group: Libraries

%description lib
lib components for the vsqlite package.


%prep
%setup -q -n vsqlite---0.3.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1516408435
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1516408435
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/sqlite/command.hpp
/usr/include/sqlite/connection.hpp
/usr/include/sqlite/database_exception.hpp
/usr/include/sqlite/execute.hpp
/usr/include/sqlite/ext/variant.hpp
/usr/include/sqlite/query.hpp
/usr/include/sqlite/result.hpp
/usr/include/sqlite/transaction.hpp
/usr/include/sqlite/view.hpp
/usr/lib64/libvsqlitepp.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libvsqlitepp.so.3
/usr/lib64/libvsqlitepp.so.3.0.0
